name: Python CI Pipeline

on:
  push:
    branches: [ main, AlirezA ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test: # CHANGED: A more descriptive job name
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # NEW: Cache dependencies for faster builds
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff # Install the linter
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # NEW: Add a linting step
    - name: Lint with ruff
      run: |
        # Stop the build if there are any linting errors
        ruff check .
        # Check formatting without changing files
        ruff format --check .

    - name: Run tests with pytest
      run: |
        python -m pytest